title: Daniel Mart√≠nez Sales
logo: /assets/img/photo.png
description: Data Scientist & Machine Learning Researcher | Healthcare Forecasting | Physicist & Mathematician
show_downloads: false
theme: jekyll-theme-minimal
